In [ ]:
import numpy as np
import pandas as pd

In [48]:
df1 = pd.DataFrame(
       {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

In [62]:
df1

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [60]:
df2 = pd.DataFrame(
     {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

In [61]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [63]:
result = pd.concat([f1, f2], axis = 1)
result

TypeError: cannot concatenate object of type '<class 'tuple'>'; only Series and DataFrame objs are valid

In [39]:
result = pd.concat([df1, f2], axis = 1)
result

      B    D    F    A    B    C    D
2    B2   D2   F2  NaN  NaN  NaN  NaN
3    B3   D3   F3  NaN  NaN  NaN  NaN
6    B6   D6   F6  NaN  NaN  NaN  NaN
7    B7   D7   F7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  A11  B11  C11  D11

In [38]:
result = pd.concat([df1, f2], axis=1, join='inner')
result

Empty DataFrame
Columns: [B, D, F, A, B, C, D]
Index: []