In [ ]:
import numpy as np
import pandas as pd

In [12]:
import pandas as pd
registration = pd.DataFrame({
    'reg_id': [1, 2, 3, 4],
    'name': ['habib', 'kibib', 'Claire', 'david']
})

logins = pd.DataFrame({
    'log_id': [1, 2, 3, 4],
    'name': ['xavier', 'andrew', 'kibib', 'david']
})

In [10]:
registration

   reg_id    name
0       1   habib
1       2   kibib
2       3  Claire
3       4   david

In [11]:
logins

   log_id    name
0       1  xavier
1       2  andrew
2       3   kibib
3       4   david

In [15]:
pd.merge(registration, logins, how='inner', on='name')

   reg_id   name  log_id
0       2  kibib       3
1       4  david       4

In [16]:
pd.merge( logins,registration, how='inner', on='name')

   log_id   name  reg_id
0       3  kibib       2
1       4  david       4